' <auto-generated />
Imports EfExample
Imports Microsoft.EntityFrameworkCore
Imports Microsoft.EntityFrameworkCore.Infrastructure
Imports Microsoft.EntityFrameworkCore.Metadata
Imports Microsoft.EntityFrameworkCore.Migrations

Namespace Global.EfExample.Migrations
    <DbContext(GetType(CustomerContext))>
    Partial Class CustomerContextModelSnapshot
        Inherits ModelSnapshot

        Protected Overrides Sub BuildModel(modelBuilder As ModelBuilder)
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8")

            modelBuilder.Entity("EfExample.Customer",
                Sub(b)
                    b.Property(Of Integer)("Id").
                        ValueGeneratedOnAdd().
                        HasColumnType("INTEGER")

                    b.Property(Of Date)("DateOfBirth").
                        HasColumnType("date")

                    b.Property(Of String)("Name").
                        HasMaxLength(150).
                        HasColumnType("TEXT")

                    b.HasKey("Id")

                    b.ToTable("Customers", DirectCast(Nothing, String))
                End Sub)

            modelBuilder.Entity("EfExample.CustomerLogin",
                Sub(b)
                    b.Property(Of Integer)("Id").
                        ValueGeneratedOnAdd().
                        HasColumnType("INTEGER")

                    b.Property(Of Date)("CreatedAt").
                        ValueGeneratedOnAdd().
                        HasColumnType("dateTime").
                        HasDefaultValueSql("datetime()")

                    b.Property(Of Integer)("CustomerId").
                        HasColumnType("INTEGER")

                    b.Property(Of Boolean)("Success").
                        HasColumnType("INTEGER")

                    b.HasKey("Id")

                    b.HasIndex("CustomerId")

                    b.ToTable("CustomerLogins", DirectCast(Nothing, String))
                End Sub)

            modelBuilder.Entity("EfExample.CustomerLogin",
                Sub(b)
                    b.HasOne("EfExample.Customer", "Customer").
                        WithMany("CustomerLogins").
                        HasForeignKey("CustomerId").
                        OnDelete(DeleteBehavior.Restrict).
                        IsRequired().
                        HasConstraintName("FK_CustomerLogins_Customer")
                    b.Navigation("Customer")
                End Sub)

            modelBuilder.Entity("EfExample.Customer",
                Sub(b)
                    b.Navigation("CustomerLogins")
                End Sub)
        End Sub
    End Class
End Namespace
